Updated Xcode CI

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -31,6 +31,8 @@ jobs:
     - uses: maxim-lobanov/setup-xcode@v1
       with:
         xcode-version: latest-stable # Sometimes a newer version of Xcode is available but isn't yet made default
+    - name: Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
+      run: xcodebuild -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "PDFGadget-CI" -resolvePackageDependencies | xcpretty && exit ${PIPESTATUS[0]}
     - name: Build
       run: xcodebuild build -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "PDFGadget-CI" -destination "generic/platform=macOS,name=Any Mac" | xcpretty && exit ${PIPESTATUS[0]}
     - name: Unit Tests
@@ -44,6 +46,8 @@ jobs:
     - uses: maxim-lobanov/setup-xcode@v1
       with:
         xcode-version: latest-stable # Sometimes a newer version of Xcode is available but isn't yet made default
+    - name: Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
+      run: xcodebuild -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "PDFGadget-CI" -resolvePackageDependencies | xcpretty && exit ${PIPESTATUS[0]}
     - name: Build
       run: xcodebuild build -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "PDFGadget-CI" -destination "generic/platform=macOS,variant=Mac Catalyst,name=Any Mac" | xcpretty && exit ${PIPESTATUS[0]}
     - name: Unit Tests
@@ -57,6 +61,8 @@ jobs:
     - uses: maxim-lobanov/setup-xcode@v1
       with:
         xcode-version: latest-stable # Sometimes a newer version of Xcode is available but isn't yet made default
+    - name: Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
+      run: xcodebuild -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "PDFGadget-CI" -resolvePackageDependencies | xcpretty && exit ${PIPESTATUS[0]}
     - name: Build
       run: xcodebuild build -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "PDFGadget-CI" -destination "generic/platform=iOS Simulator,name=Any iOS Device" | xcpretty && exit ${PIPESTATUS[0]}
     - name: Unit Tests
@@ -70,6 +76,8 @@ jobs:
     - uses: maxim-lobanov/setup-xcode@v1
       with:
         xcode-version: latest-stable # Sometimes a newer version of Xcode is available but isn't yet made default
+    - name: Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
+      run: xcodebuild -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "PDFGadget-CI" -resolvePackageDependencies | xcpretty && exit ${PIPESTATUS[0]}
     - name: Build
       run: xcodebuild build -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "PDFGadget-CI" -destination "generic/platform=tvOS Simulator,name=Any tvOS Simulator Device" | xcpretty && exit ${PIPESTATUS[0]}
     - name: Unit Tests
@@ -83,6 +91,8 @@ jobs:
     - uses: maxim-lobanov/setup-xcode@v1
       with:
         xcode-version: latest-stable # Sometimes a newer version of Xcode is available but isn't yet made default
+    - name: Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
+      run: xcodebuild -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "PDFGadget-CI" -resolvePackageDependencies | xcpretty && exit ${PIPESTATUS[0]}
     - name: Build
       run: xcodebuild build -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "PDFGadget-CI" -destination "generic/platform=watchOS,name=Any watchOS Device" | xcpretty && exit ${PIPESTATUS[0]}
     - name: Unit Tests
